language: node_js
node_js:
- '8'
install: yarn install
script:
- yarn test
- "./dapperdox.sh"
deploy:
  provider: heroku
  api_key:
    secure: dOpI9S3r88hxhzwSZxfHjGB+NL2WE5lSpe742hSxVrplafCrkkyC/TRx9qWo1y/FlEgH72eAKAEMxyF8m70wCvu+SOPe3WeNb2oQLPJbGF9p1eh079K2r7ukTWRkoB1WioaUKTkRt+dwT28h2EQOPD1UqkKcscM/ov+AwuWcSiENkvPfEw4O8V27LhLkZNC0MVtD66RVDb1ZL0ysgz/fVJAbJzU6FZuCzsEZsV5AwvSTFm7mzSiu7nFwrsw9oeSqg1mgmyClIV0mnnTilqtk8Kydqs5iluUyujqm/94ovK/BOLtBISjpITTezqBLy8lBwionRbWPsJc5qZd/D7fYsJevB4F50+QVsWQwns8D1F7rOPnpMGKvVsV7X8etP+mtTlRNAyaUIJutrISP1iQp7KWw7PUGww+17Wk3ORxO5qT3y/TLQymn1QF7+u6KLb7AxWzB9AjhwYcMUu5R2lIbYW5q7fSmFM0ayAuBTxqAMIBZRqDFvjqptA+qTG8V+swRUEuq/iF0Y0F6cmhsThZSatlKOL+8N5Fc0ekGgCXUCUENCYK9TFOZBCuWNSJV6kmD7bJXQnmtxTJSULad2wt+k6oLO1dpGddgiMimG2k4SpI3y2wkbMkp3oD1wW/Ww6FLm3ifmZrZyggRWXlW1RQ8ItgsY9ZRV/ovC0w4c8ZKnhE=
  app: uwa-model
  skip_cleanup: true
  on: master
