swagger: "2.0"
x-navigateMethodsByName: true
info:
  title: Unleashed Web Api
  description: This is an API for our frontends and users to interact with Unleashed
  version: "0.5"
host: api.unleashed.be
basePath: /stievie
tags:
  - name: Authentication
    description: Authentication
  - name: Authorizations
    description: Authorizations
  - name: Customers
    description: Customers
  - name: Password
    description: Passwords
  - name: Email
    description: Email
  - name: Products
    description: Products
  - name: Subscriptions
    description: Subscriptions
  - name: Telco
    description: Telco
  - name: Finance
    description: Finance
  - name: Mandates
    description: Mandates
  - name: Orders
    description: Orders
  - name: Apps
    description: App
  - name: Point of sale
    description: Partners
  - name: Loyalty Points
    description: Loyalty Points
schemes:
  - https
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
parameters:
  $ref: ./parameters/index.yaml
