type: object
title: Product
required:
  - id
  - price
  - type
  - descriptions
properties:
  id:
    $ref: '#/definitions/ProductId'
  descriptions:
    $ref: '#/definitions/Descriptions'
  price:
    description: >
      price of the item, expressed as a decimal number of Euros or Vikingpoints.  For free items, the value 0 must be
      present.
    type: number
  product_definitions:
    description: >
      The definition of the different values that make up the product. It is up the the client to interpret the keys.
    type: object
    properties:
      rates:
        description: >
          The charging rates of different services in the product. These are expressed as decimals, with the
          unit being euros. Probable keys are voice, sms, data, mms, voice_super_on_net, sms_super_on_net.
        type: object
      bundles:
        description: >
          The amount of units in the different bundles of the product. These are expressed as integers, with the unit
          depending on the service of the bundle. Probable keys are voice, sms, data, mms, voice_super_on_net,
          sms_super_on_net.
        type: object
      bundle_prices:
        description: >
          The prices for bundles in the product. These are expressed as decimals, with the unit being euros.
        type: object
  type:
    description: >
      Type of the product represented as a hierarchical (slash-separated) string (e.g. topup, subscription/postpaid,
      hardware/handset).  This can be used to filter on certain types, or to group products.
    type: string
