type: object
title: Auto topup settings
description: Auto-topup settings
required:
  - triggers
properties:
  triggers:
    description: A list of trigger properties that might trigger a topup
    type: array
    items:
      $ref: '#/definitions/AutoTopupTrigger'
  mandate_id:
    type: string
    description: The id of the mandate that will be used to pay the automatic topup when it takes place.
  product_id:
    type: string
    description: The if of the product that will be used to topup when an automatic topup takes place. Optional if and only if every type of auto topup is completely disabled.
  allow_sms_topup:
    type: boolean
    default: false
    description: Whether or not to allow topup via SMS
  use_loyalty_points_first:
    type: boolean
    default: false
    description: Whether or not if possible first use loyalty points to do topup
